= SEF Facebook Live Technical Guidelines

=== The equipments you would need for a Facebook Live Broadcast.
1. A Computer or a Laptop
* If you are using a desktop  *computer* then you would need a  *webcam and a microphone*.
* If you are using a  *Laptop* then you can use *inbuilt webcam and the microphone*.
+
NOTE: Can you use a mobile phone? Well, yes, but we don't recommend it due to several reasons, including the fact that it is difficult to handle.

2. Internet Connection
* You would be needing *a good internet connection* since a fast upload speed is important for an uninterrupted broadcast of the live video.

=== Tools or Software required for a Facebook Live Broadcast.

* If you are going to conduct the Live Broadcast *without any slides*, then you could *directly go live* on Facebook using your web browser.(We highly recommend Google Chrome).

* If you have any *slides or any third party content* like videos,photos and etc to present during the live broadcast, then you would be needing a live broadcasting tool that allows you to share your screen.(we recommend *https://obsproject.com/[OBS Studio]* which is available on both Windows and Mac). 

* You can follow this *https://www.youtube.com/watch?v=rapsYGqHsUA[Video Tutorial]* for step by step guidance on live streaming using OBS Studio.                

=== Rehearsal for the Facebook Live Broadcast.

NOTE: Before going live on SEF FB page, we highly recommend you to conduct a *rehearsal*.

* For this purpose we have a created a secret *https://www.facebook.com/groups/1894626114136612/[Facebook group]* where you can go live as a rehearsal.
You don’t need to do the full session here , the purpose of this rehearsal  is to assure that your FB Live setup is working fine.
* SEF team members will give you feedback on the rehearsal.

=== Going Live on *https://www.facebook.com/sustainableeducationfoundation/[SEF FB Page]*

* We will be providing you access to the *SEF FB Page as an editor* which would provide you with the access privileges to go live on  SEF FB page.

=== Compilation Credits
https://github.com/hasitha95[Hasitha Senevirathne]
